name: CI
on: push

jobs:
  web:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Unit Tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: npm run test
      - name: Formatting
        run: npm run prettier-check
      - name: Build
        run: npm run build
